version: "3"
services:
    c1:
        build: c1
        ports:
            - "5000:5000"
        volumes:
            - ./c1:/app # modified here to take into account the new app path
        links:
            - db
            - c2

    c2:
        build: c2
        ports:
            - "5001:5001"
        volumes:
            - ./c2:/app # modified here to take into account the new app path
        links:
            - db
            - c1

    db:
        image: postgres