version: "3"
services:
    c1:
        build: c1
        ports:
            - "5000:5000"
        links:
            - "c2"
        depends_on:
            - "c2"
        restart: on-failure
        environment:
            LOGGING_KEY: 

    c2:
        build: c2
        depends_on:
            - "db"
        restart: on-failure
        environment:
            PORT: 5001
            DATABASE_URI: "postgresql://user:pass@db:5432/db"
            LOGGING_KEY: 

    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: user
            POSTGRES_DB: db
